#!/bin/bash

echo "🚨 CRITICAL RAZORPAY TROUBLESHOOTING 🚨"
echo "========================================"
echo ""
echo "If you're only seeing Cards and Netbanking, follow these steps:"
echo ""

echo "STEP 1: CHECK YOUR RAZORPAY DASHBOARD"
echo "--------------------------------------"
echo ""
echo "1. Open: https://dashboard.razorpay.com"
echo "2. Login with your account"
echo "3. Click on 'Account & Settings' (gear icon on left sidebar)"
echo "4. Click on 'Payment Methods'"
echo ""
echo "YOU MUST SEE THIS:"
echo "  ✅ Cards - ENABLED"
echo "  ✅ UPI - ENABLED ← MOST IMPORTANT"
echo "  ✅ Wallets - ENABLED"
echo "  ✅ Net Banking - ENABLED"
echo ""
echo "⚠️  IF UPI IS DISABLED:"
echo "   1. Click the toggle to ENABLE it"
echo "   2. Save changes"
echo "   3. Wait 5 minutes for changes to sync"
echo "   4. Rebuild your app"
echo ""
echo "========================================"
echo ""

echo "STEP 2: CHECK TEST MODE vs LIVE MODE"
echo "--------------------------------------"
echo ""
echo "In your Razorpay dashboard, look at top-right corner:"
echo "  • Is 'Test Mode' enabled?"
echo "  • Or is 'Live Mode' enabled?"
echo ""
echo "Your Key: rzp_live_SObcQvFXRo6HAa"
echo "This is a LIVE key (starts with rzp_live_)"
echo ""
echo "⚠️  MAKE SURE:"
echo "   • Dashboard is in LIVE MODE"
echo "   • OR use a TEST key if testing"
echo ""
echo "========================================"
echo ""

echo "STEP 3: VERIFY PAYMENT METHODS ARE ACTIVATED"
echo "--------------------------------------"
echo ""
echo "In Payment Methods page, for each method:"
echo ""
echo "UPI:"
echo "  □ Is UPI toggle ON?"
echo "  □ Do you see 'Active' status?"
echo "  □ Is there a 'Not Available' message?"
echo ""
echo "Wallets:"
echo "  □ Is Wallets toggle ON?"
echo "  □ Which wallets are enabled?"
echo ""
echo "========================================"
echo ""

echo "STEP 4: CHECK ACCOUNT ACTIVATION STATUS"
echo "--------------------------------------"
echo ""
echo "Some payment methods require:"
echo "  1. KYC verification complete"
echo "  2. Account fully activated"
echo "  3. Business details submitted"
echo ""
echo "Check your Razorpay dashboard home:"
echo "  • Is your account 'Activated'?"
echo "  • Are there any pending verifications?"
echo "  • Any restrictions shown?"
echo ""
echo "========================================"
echo ""

echo "STEP 5: COMMON ISSUES & FIXES"
echo "--------------------------------------"
echo ""
echo "Issue 1: UPI shows in web but not in mobile app"
echo "Fix: This is correct! UPI apps only appear on mobile devices"
echo "     with UPI apps installed (PhonePe, GPay, etc.)"
echo ""
echo "Issue 2: Only Cards and Netbanking show"
echo "Fix: UPI is disabled in Razorpay dashboard"
echo "     Go to Settings → Payment Methods → Enable UPI"
echo ""
echo "Issue 3: 'Payment method not available'"
echo "Fix: Account not fully activated or method not supported"
echo "     Contact Razorpay support to enable"
echo ""
echo "Issue 4: Changes not reflecting in app"
echo "Fix: After enabling methods in dashboard:"
echo "     1. Wait 5 minutes"
echo "     2. Rebuild app: yarn build"
echo "     3. Reinstall: npx cap sync android && npx cap run android"
echo ""
echo "========================================"
echo ""

echo "STEP 6: CONTACT RAZORPAY SUPPORT"
echo "--------------------------------------"
echo ""
echo "If UPI is enabled in dashboard but still not showing:"
echo ""
echo "Email: support@razorpay.com"
echo "Subject: UPI not showing in Razorpay Checkout"
echo ""
echo "Include in email:"
echo "  • Your Razorpay Account ID"
echo "  • Your website: ember-progress.vercel.app"
echo "  • API Key: rzp_live_SObcQvFXRo6HAa"
echo "  • Issue: UPI section not appearing in checkout"
echo "  • Screenshot of Payment Methods page"
echo ""
echo "========================================"
echo ""

echo "✅ NEXT STEPS TO TRY:"
echo ""
echo "1. Enable UPI in Razorpay Dashboard (Settings → Payment Methods)"
echo "2. Wait 5 minutes after enabling"
echo "3. Rebuild app: cd frontend && yarn build"
echo "4. Sync: npx cap sync android"
echo "5. Run: npx cap run android"
echo "6. Test again"
echo ""
echo "If still not working after enabling UPI:"
echo "  → Contact Razorpay support"
echo "  → Your account might need activation for UPI"
echo ""
echo "========================================"
